# 使用语言
language: node_js  #设置语言

node_js: 
- 8.11  #设置相应的版本

cache:
    apt: true
    directories:
        - node_modules # 缓存不经常更改的内容

before_install:
- npm install -g hexo-cli

install:
- npm install

script:
- hexo clean
- hexo generate
after_success:
- git config --global user.name "xigaohu"
- git config --global user.email "xigaohu@163.com"
- sed -i'' "/^ *repo/s~github\.com~${repo_token}@github.com~" _config.yml
- hexo deploy