# 使用语言
language: node_js  #设置语言

node_js: 
- 8.11  #设置相应的版本

cache:
    apt: true
    directories:
        - node_modules # 缓存不经常更改的内容

before_install:
- npm install -g hexo-cli

install:
- npm install

script:
- hexo clean
- hexo generate

branches:
  only:
    - hexo  #只监测hexo分支，hexo是我的分支的名称，可根据自己情况设置

after_script:
  - cd ./public
  - git init
  - git config --global user.name "xigaohu"
  - git config --global user.email "xigaohu@163.com"
  - git add .
  - git commit -m "update by travis"
  - git push --force --quiet "https://${repo_token}@github.com/xigaohu/xigaohu.github.io.git" master:master
